### PR TITLE
Update ShareModal.js WhatsApp link

### PR DESCRIPTION
**Pull request by Hari-Bonda**
wa.me URL is not working on mobile.

api.whatsapp.com/send/?phone&text=

### CODE REVIEW

**Comment by Hari-Bonda** [comment]
> It works for me. The existing URL redirects to the one you're replacing it with.

I have tested using opera's mobile browser but it is not getting redirected. my flarum is in a sub directory, not on a subdomain.

**Comment by datitisev** [comment]
@Hari-Bonda I don't think that should matter... Does just going to `wa.me` work at all? That redirects me to `https://api.whatsapp.com/`.

**Comment by datitisev** [comment]
@Hari-Bonda Is this still an issue?

**Comment by Hari-Bonda** [comment]
it is still not working, if possible could you test this manually.

image

**Comment by datitisev** [comment]
So the issue of `wa.me` not resolving is fixed. Now the problem is that it seems to require `?phone&` - I'll do that update by itself as I think using the short domain is best.

**Comment by datitisev** [comment]
Actually, I will not. Looks like they've done something to the short URL making it not work. I'll merge this. Thanks!

**Comment by Hari-Bonda** [comment]
> Actually, I will not. Looks like they've done something to the short URL making it not work. I'll merge this. Thanks!

I see the PR is merged but how can I update it? (i am new to GitHub)
 i am using v1.1.0, could you push an update

**Comment by datitisev** [comment]
Version v1.1.0 is the update I pushed with those changes.

**Comment by Hari-Bonda** [comment]
My flarum is still picking the old URL i have cleared the flarum cache too.

**Comment by datitisev** [comment]
I... don't know what to say. Looking at the code in general and that for 1.1.0, the URL has been changed _and_ the JS has been compiled in the tagged version.

You sure you're running 1.1.0?

**Comment by Hari-Bonda** [comment]
Yes, I just disabled and pressed the purge button. now everything is working fine.

Solved ✅ thanks

**Pull request merged**
